apiVersion: v1
kind: Service
metadata: 
  name: echo-server-cluster-ip
  labels: 
    component: echo-server
spec: 
  type: LoadBalancer
  ports: 
    - port: 80
      nodePort: 30000
      targetPort: 5000
  selector: 
    component: echo-server
  externalTrafficPolicy: Cluster