apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: echo-server
  template:
    metadata:
      labels:
        component: echo-server
    spec:
      containers:
        - name: echo-server
          image: progmichaelkibenko/echo-server
          ports:
            - containerPort: 5000